### ISSUE TITLE
「テーマファイル」を「テーマパッケージ」に修正する

### ISSUE THREAD

**Issue by ogwata** [vivliostyle/docs.vivliostyle.org#11]
やましーさん

[特集企画：Create Book で同人誌を作ろう！](https://vivliostyle.org/ja/make-books-with-create-book/)、及び [Let's self-publish with Create Book!](https://vivliostyle.org/make-books-with-create-book/)において、テーマファイル（theme file）をテーマパッケージ（theme package）に置換してください。

Ⅰヵ所チュートリアルへのリンクがありますが、すでに [vivliostyle /
docs.vivliostyle.org ](https://github.com/vivliostyle/docs.vivliostyle.org)の修正はすんでいるので、そのまま置換して大丈夫です。

なお、英語ページにはⅠヵ所だけ複数形の “theme files” がありますのでご注意ください。

**Comment by MurakamiShinyu** [comment]
このissue開いたままですが解決済みですね
