### ISSUE TITLE
Documentation links

### ISSUE THREAD

**Issue by withanage** [vivliostyle/docs.vivliostyle.org#15]
Dear team,
I have seen two missing links in the documentation.

https://github.com/vivliostyle/docs.vivliostyle.org#references

Supported CSS Features
Core API Reference

**Comment by MurakamiShinyu** [comment]
Hi @withanage 

This repository is for making the document site <https://docs.vivliostyle.org>, using [Docute](https://docute.org/). So the README.md file in this repository is converted to the home page of the site. See <https://docs.vivliostyle.org>.

**Comment by withanage** [comment]
Thanks @MurakamiShinyu  for clarification.
